name: Print Docstrings of Edited Functions

on:
  pull_request:
    branches: [main]
    paths:
      - "**.py"

jobs:
  print-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch main
        run: |
          git fetch origin ${{ github.head_ref }}
          git fetch origin ${{ github.base_ref }}
          git checkout origin ${{ github.head_ref }}
          git checkout -
          git checkout origin/${{ github.base_ref }}
          git checkout -

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # Any other dependencies your script needs

      - name: Print Modified Functions' Docstrings
        run: python action.py
        env:
          PR_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.base_ref }}
